### ISSUE TITLE
fpocket 4.0.0 failed to compile on macOS 15.5

### ISSUE THREAD

**Issue by mys721tx** [brewsci/homebrew-bio#2071]
The upstream said to use `ARCH=MACOSXARM64 make` but I was not able to get it to work.

```ShellSession
$ brew install brewsci/bio/fpocket
==> Fetching downloads for: fpocket
==> Fetching brewsci/bio/fpocket
==> Downloading https://github.com/Discngine/fpocket/archive/refs/tags/4.0.0.tar
Already downloaded: /Users/mys_721tx/Library/Caches/Homebrew/downloads/e790538332053039758108bec6f319a961f199e32635ea29e1d00840b14ba591--fpocket-4.0.0.tar.gz
==> Installing fpocket from brewsci/bio
==> make ARCH=MACOSXX86_64
Last 15 lines from /Users/mys_721tx/Library/Logs/Homebrew/fpocket/01.make:
      _read_topology in topology.o
  "_molfile_parm7plugin_register", referenced from:
      _read_topology in topology.o
  "_molfile_pdbxplugin_init", referenced from:
      _open_mmcif in read_mmcif.o
      _read_mmcif in read_mmcif.o
  "_molfile_pdbxplugin_register", referenced from:
      _open_mmcif in read_mmcif.o
      _read_mmcif in read_mmcif.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/tpocket] Error 1
make: *** [bin/dpocket] Error 1
chmod +x eg/q_test eg/q_eg eg/q_egtest

```

```
HOMEBREW_VERSION: 4.5.13-97-ga7ea27a
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7ea27a9c81660931a9796edc63d8533dfb1da26
Last commit: 6 hours ago
Branch: main
Core tap HEAD: d5ef88d3b4d8088c691783bee3654727e4ea42db
Core tap last commit: 11 hours ago
Core tap JSON: 05 Aug 07:13 UTC
Core cask tap HEAD: 885bf23bf37c350adca6c3d007cb84f76ab2bb84
Core cask tap last commit: 11 hours ago
Core cask tap JSON: 05 Aug 07:13 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.N7BeJ1HRj4/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/bin/ruby
CPU: deca-core 64-bit arm_firestorm_icestorm
Clang: 17.0.0 build 1700
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.5-arm64
CLT: 16.4.0.0.1.1747106510
Xcode: 16.4
Rosetta 2: false

```
